#common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: ZDliNzg1ODU5ZjlkYzdlNGY0MWQ3NWRiNTkwYzhjYmZlMmE5YTZhYTdjNzA0MDAzNzhhYzliMGNhNzk5NjExNGI2ZTU5ZmNlN2IzY2E3MTgzYjY0NzVmYjVjYTcxM2ZiYjk1Nw==

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
